export const ProductApiStructure = {
  'product._id': "",
  'product.productTitle': "",
  'product.description': "",
  'product.longDescription': "",
  'product.tags': "",
  'product.brand': "",
  'product.category': "",
  'product.unit': "",
  'product.pageTitle': "",
  'product.sku': "",
  'product.isVariant': "",
  'product.metaTitle': "",
  'product.metaKeywords': "",
  'product.metaDescription': "",
  'product.ogTitle': "",
  'product.ogDescription': "",
  'product.twitterTitle': "",
  'product.twitterDescription': "",
  'product.productImageUrl': "",
  'product.productImage': "",
  'product.galleryImage[0]': "",
  'product.removedGalleryImages[0]': "", 
  'product.completeTab': "",

  'product.measurements.weight': "",
  'product.measurements.height': "",
  'product.measurements.length': "",
  'product.measurements.width': "",

  'product.variants[][countryId]': "", 
  'product.variants[][variantSku]': "",
  'product.variants[][price]': "", 
  'product.variants[][extraProductTitle]': "", 
  'product.variants[][discountPrice]': "", 
  'product.variants[][quantity]': "", 
  'product.variants[][isDefault]': "", 
  'product.variants[][variantDescription]': "", 
  'product.variants[][cartMinQuantity]': "", 
  'product.variants[][cartMaxQuantity]': "", 
  'product.variants[][hsn]': "", 
  'product.variants[][mpn]': "",
  'product.variants[][barcode]': "", 
  'product.variants[][galleryImage][]': "", 
  'product.variants[][variantImage]': "",

  'product.variants[][productVariantAttributes][][attributeId]': "", 
  'product.variants[][productVariantAttributes][][attributeDetailId]': "", 

  'product.variants[][specificationId]': "", 
  'product.variants[][specificationDetailId]': "", 

  'product.productSpecification[].specificationId': "", 
  'product.productSpecification[].specificationDetailId': "", 

  'product.productSeo.metaTitle': "",
  'product.productSeo.metaKeywords': "",
  'product.productSeo.metaDescription': "",

  "ogTitle": "",
  "ogDescription": "",
  "twitterTitle": ""
};
