export const fakeData = [
    {
      id: 1,
      customerName: "iqthiyar",
      email: "iqthibm@gmail.com",
      phone: "971567534622",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 2,
      customerName: "jafarpib",
      email: "jafarpb@gmail.com",
      phone: "971562263918",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 3,
      customerName: "Amneh alabboud",
      email: "yaraboura799@gmail.com",
      phone: "971501984157",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 4,
      customerName: "Siddeekh",
      email: "siddeekhddf@yahoo.in",
      phone: "971504960518",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 5,
      customerName: "Amer",
      email: "almousa2001@gmail.com",
      phone: "0504218655",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 6,
      customerName: "Guest",
      email: "abdullah276@hotmail.com",
      phone: "0508732038",
      orderTotalAmount: "AED 275.71",
      totalOrderCount: 1,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 7,
      customerName: "Zara",
      email: "zara@gmail.com",
      phone: "971508356354",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 8,
      customerName: "Vipin",
      email: "gopal.vipin@gmail.com",
      phone: "0569799147",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 9,
      customerName: "Kader",
      email: "kaderdeens@gmail.com",
      phone: "971551440706",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 10,
      customerName: "Zara",
      email: "zara@gmail.com",
      phone: "05443359521",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "rejected",
    },
    {
      id: 11,
      customerName: "Sara",
      email: "sara@yahoo.com",
      phone: "971544358521",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 12,
      customerName: "Labdullah",
      email: "abdullahmakrm@gmail.com",
      phone: "971505193941",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 13,
      customerName: "Mohammed Sirajudheen K",
      email: "sirajmdry70@gmail.com",
      phone: "971508096277",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 14,
      customerName: "Bilal",
      email: "bilal@gmail.com",
      phone: "971569426885",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 15,
      customerName: "Tabe Colins",
      email: "tabecolins@gmail.com",
      phone: "971558407351",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
    {
      id: 16,
      customerName: "Deepa",
      email: "deepababu@gmail.com",
      phone: "0553056354",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "desktop",
      isVerified: "verified",
    },
    {
      id: 17,
      customerName: "Anisha syed",
      email: "anishasyed24@gmail.com",
      phone: "971528303799",
      orderTotalAmount: "AED 0.00",
      totalOrderCount: 0,
      deviceType: "mobile",
      isVerified: "verified",
    },
  ];

  export   const columns = [
    {
      id: "customerName",
      label: "CUSTOMER NAME",
    },
    {
      id: "email",
      label: "EMAIL",
    },
    {
      id: "phone",
      label: "PHONE",
    },
    {
      id: "orderTotalAmount",
      label: "ORDER TOTAL AMOUNT",
    },
    {
      id: "totalOrderCount",
      label: "TOTAL ORDER COUNT",
    },
    {
      id: "deviceType",
      label: "DEVICE TYPE",
    },
    {
      id: "isVerified",
      label: "IS VERIFIED",
      render: (row: any) => (
        <>
          {row.isVerified === "verified" ? (
            <CheckCircleIcon color="success" />
          ) : (
            <CancelIcon color="error" />
          )}
        </>
      ),
    },
  ];
