import { CartState } from "@/types/store/cart-types";

export const initialState: CartState = {
  cart_hash: "",
  cart_key: "",
  currency: {
    currency_code: "",
    currency_symbol: "",
    currency_symbol_pos: "",
    currency_minor_unit: null,
    currency_decimal_separator: "",
    currency_thousand_separator: "",
    currency_prefix: "",
    currency_suffix: "",
  },
  customer: {
    billing_address: {
      billing_first_name: "",
      billing_last_name: "",
      billing_company: "",
      billing_country: "",
      billing_address_1: "",
      billing_address_2: "",
      billing_city: "",
      billing_state: "",
      billing_postcode: "",
      billing_phone: "",
      billing_email: "",
    },
    shipping_address: {
      shipping_first_name: "",
      shipping_last_name: "",
      shipping_company: "",
      shipping_country: "",
      shipping_address_1: "",
      shipping_address_2: "",
      shipping_city: "",
      shipping_state: "",
      shipping_postcode: "",
      shipping_phone: "",
    },
  },
  items: [],
  item_count: 0,
  items_weight: "",
  coupons: [],
  needs_payment: false,
  needs_shipping: false,
  shipping: [],
  fees: [],
  taxes: [],
  totals: {
    subtotal: "",
    subtotal_tax: "",
    fee_total: "",
    fee_tax: "",
    discount_total: "",
    discount_tax: "",
    shipping_total: "",
    shipping_tax: "",
    total: "",
    total_tax: "",
  },
  removed_items: [],
  cross_sells: [],
  notices: [],
  // images: {},
  selected_country: "",
  int_shipping_charge: 0, // Additional shipping charge for international shipping
};
